baseURL = "https://zisai.com/"
languageCode = "zh-cn"
title = "紫塞 zisai.com"
theme = "hugo-theme-stack"

[module.hugoVersion]
extended = true
min = "0.87.0"

[params]
mainSections = ["posts"]
favicon = "/favicon.ico"

[params.footer]
since = 1998

[params.sidebar.avatar]
enabled = true
local = true
src = "/images/avatar.png"