baseURL = "https://zisai.com/"
theme = "stack"
title = "紫塞 zisai.com"
languageCode = "zh-CN"
languageName = "简体中文"
enableRobotsTXT = true  # 启用机器人协议
enableGitInfo = true    # 显示Git提交信息（可选）
builddrafts = false

[author]
  name = "SHENNAN"
  email = "mythflair@hotmail.com"
  link = "https://baike.baidu.com/item/%E6%B2%88%E6%A5%A0/49988317"
  avatar = "/images/avatar.jpg"  # 新增头像路径

# 首页优化配置
[params.home]
  subtitle = "记录技术与思考的角落"  # 首页副标题
  recentPosts = 10           # 显示最新文章数量
  showFeatured = true        # 显示精选文章
  showCategories = true      # 显示分类云
  showTags = true            # 显示标签云

# 新增SEO优化
[params.seo]
  image = "/images/og-image.png"  # Open Graph默认图片
  twitter = "@Mythflair"          # Twitter账号（可选）

# 新增评论系统（使用Utterances）
[params.comments]
  enabled = true
  repo = "Mythflair/zisai.com"  # 替换为你的仓库
  issueTerm = "pathname"

# 新增分析统计
[params.analytics]
  google = "G-XXXXXX"  # 替换为你的GA4 ID

# 菜单优化（增加图标支持）
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "📚 文章"
    url = "/posts/"
    pre = "<i class='fas fa-book'></i>"  # Font Awesome图标
  [[menu.main]]
    weight = 2
    identifier = "tags"
    name = "🏷️ 标签"
    url = "/tags/"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    name = "🗂️ 分类"
    url = "/categories/"
  [[menu.main]]
    weight = 4
    identifier = "about"
    name = "👤 关于"
    url = "/about/"

# 新增社交链接
[params.social]
  github = "Mythflair"
  email = "mythflair@hotmail.com"
  zhihu = "shen-nan-74"  # 知乎账号

# 新增文章目录配置
[params.toc]
  enabled = true    # 自动生成目录
  depth = 3         # 目录层级深度
  sticky = true     # 浮动目录

# 新增打赏功能（按需启用）
[params.reward]
  enable = true
  wechat = "/images/wechat-reward.jpg"
  alipay = "/images/alipay-reward.jpg"