# Hugo 站点基础配置
baseURL = "https://zisai.com/"  # 站点根 URL，用于生成绝对链接
languageCode = "zh-cn"  # 站点语言，zh-cn 表示中文（简体）
title = "紫塞 zisai.com"  # 站点标题，显示在页面标题和导航中
theme = "PaperMod"  # 使用的主题名称

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true

  [params.profileMode]
    enabled = true
    title = "紫塞" # 可选，默认使用站点标题
    subtitle = "忠于技术，追寻理想" # 可选，默认使用站点副标题
    description = "记录技术与思考的角落" # 可选，默认使用站点描述
    imageUrl = "/images/shennan.jpg" # 替换为你的图片路径
    imageTitle = "SHENNAN"
    imageWidth = 120
    imageHeight = 120
    [[params.profileMode.buttons]]
      name = "文章归档"
      url = "/archive"
    [[params.profileMode.buttons]]
      name = "GitHub"
      url = "https://github.com/mythflair"

    [[params.socialIcons]]
      name = "email"
      url = "mailto:mythflair@hotmail.com"
    [[params.socialIcons]]
      name = "GitHub"
      url = "https://github.com/mythflair"

    [[menu.main]]
      identifier = "posts"
      name = "📝 文章"
      url = "/posts/"
      weight = 10
    [[menu.main]]
     identifier = "story"
     name = "🗂️ 故事"
     url = "/story/"
     weight = 20
    [[menu.main]]
      identifier = "about"
      name = "ℹ️ 关于"
      url = "/about/"
      weight = 30
[outputs]
  home = ["HTML", "RSS", "JSON"]